use INFORMATION_SCHEMA;

select TABLE_NAME, COLUMN_NAME, CONSTRAINT_NAME, REFERENCED_TABLE_NAME, REFERENCED_COLUMN_NAME
from KEY_COLUMN_USAGE
where TABLE_SCHEMA = $db and TABLE_NAME = $table
and referenced_column_name is not NULL;